// Copyright 2025-2026 H2O.ai, Inc.
// SPDX-License-Identifier: Apache-2.0

// Supplemental syntax from command-handler Usage responses. Live catalog help is
// merged with these forms, so descriptive help never hides handler parameters.
export const COMMAND_USAGE: Record<string, string[]> = {
  ls: ["ls", "ls rooms", "ls entities", "ls <room-id>"],
  look: ["look [target]"],
  goto: ["goto <room-id|entity-name>"],
  say: ["say <message>"],
  shout: ["shout <message>"],
  tell: [
    "tell <entity> [ttl:30s] <message>   (also --ttl=30s)",
    "tell <entity> [ttl:30s] <message> | tell inbox | tell status <id> | tell ack <id>\n(ttl also accepts --ttl 30s / --ttl=30s; units 30s, 5m, 2h, 1d)",
  ],
  help: ["help", "help <command> [full]", "help all", "help <category>"],
  image: [
    "image generate <prompt...> [model:<provider/model>] [style:<style>] [width:<px>] [height:<px>] [canvas:<name>] (also --width 1024)",
    "image generate <prompt...> [style:synthwave] [width:1024] [canvas:name]",
    "image generate <prompt...>",
  ],
  video: [
    "video generate <prompt...> [--model provider/model] [--duration <s>] [--fps <frames>] [--reference <asset>] [--canvas <name>]",
    "video generate <prompt...>",
  ],
  emote: ["emote <action>"],
  calc: ["calc <expression>. End with the value you want returned."],
  ignore: ["ignore <name> | ignore list | ignore remove <name>", "ignore remove <name>"],
  brief: ["brief", "brief full", "brief social", "brief watch [interval]", "brief unwatch"],
  rank: ["rank", "rank <entity>", "rank <entity> <level>"],
  provenance: [
    "provenance",
    "provenance status",
    "provenance list [journey-id]",
    "provenance verify [count]",
  ],
  probe: ["probe", "probe <kind> <key>:<value> [<additional key:value pairs>]"],
  watch: [
    "watch create <kind> <key>:<value> [<additional key:value pairs>] [cadence:<duration>] [retirement:<policy>] [notify:<entity-or-channel>]",
    "watch list",
    "watch show <id>",
    "watch due [limit:<N>]",
    "watch retire <id> [reason:<text>]",
  ],
  quest: ["quest list", "quest start <name>", "quest status", "quest complete", "quest abandon"],
  link: ["link | link status | link unlink <adapter>", "link unlink <telegram|discord>"],
  note: [
    "note <text> | note claim <text> [confidence:0..1] [source:URL] (also trailing `confidence 0.9 source URL`) | note explain|verify|source|contradictions|consolidate ... | note list (ls) | note delete <id> (rm/remove)",
    "note <text> [importance N] [type T] | note list | note room | note search <query> | note delete <id> | note link <id1> <id2> <rel> | note unlink <id1> <id2> <rel> | note correct <id> <text> | note trace <id> | note graph | note evolve <id> | note types\n",
    "note claim <text> [confidence:0..1] [source:URL] [observed:YYYY-MM-DD]   (also trailing `confidence 0.9 source URL`)\n",
    "note source <your-note-id> <url|note:id> [type T] [credibility 0..1] [observed YYYY-MM-DD]\n",
    "note derive <your-note-id> <source-note-id>",
    "note verify <your-note-id> unverified|verified|disputed [confidence 0..1]",
    "note resolve <case-id> left|right|both|neither <evidence-backed rationale>\n",
    "note consolidate <keeper-id> <duplicate-id> [duplicate-id ...]",
    "note search <query>",
    "note delete <id>",
    "note link <id1> <id2> <relationship>",
    "note unlink <id1> <id2> <relationship>",
    "note correct <id> <new text>",
    "note trace <id>",
    "note <text> importance <N> type <type>",
    "note evolve <id>",
    "note <text>",
  ],
  association: [
    "association create <name> | <purpose>",
    "association revise <association> | <relation-id> | <kind>:<ref> | <directed|reciprocal> | <semantics> | <kind>:<ref> [| JSON terms or text]",
    "association relate <association> | <kind>:<ref> | <directed|reciprocal> | <semantics> | <kind>:<ref> [| JSON terms or text]",
    "association link <association> | <canonical-kind>:<ref> | <relationship>",
  ],
  desire: [
    "desire <what you want to explore, understand, decide, improve, or create>",
    "desire <one sentence>",
  ],
  chronicle: [
    "chronicle show <id>",
    "chronicle about <name>",
    "chronicle record <title> | <body> refs <feed:N,task:N,...> [participants <names>]",
    "chronicle correct <id> <title> | <body> [refs <ids>]",
    "chronicle correct <id> <title> | <body> [refs <ids>] [participants <names>]",
    "chronicle digest day|week <title> | <body> [refs <ids>] [period <token>]",
  ],
  search: ["search <query>"],
  bookmark: [
    "bookmark | bookmark list | bookmark note <#> <text> | bookmark delete <#>",
    "bookmark note <#> <text>",
    "bookmark delete <#>",
  ],
  memory: [
    "memory kv list | memory kv set <key> <value> | memory kv get <key> | memory kv delete <key> | memory kv history <key> | memory kv clear\n",
  ],
  recall: [
    "recall <query> [recent|important|trusted|explain|evidence|all] [type <type>] [budget <bytes>]\n  all \u2014 unified tiers: skills, [trusted], [evidence] (durable records + sources), [proposal] (assistance answers), [unverified]\n  evidence \u2014 durable tiers only",
    "recall <query> [recent | important] [type <type>]",
  ],
  reflect: [
    "reflect [topic] [--share <pool>] [--no-spawn]",
    "reflect via <helper> [topic] [--share <pool>]",
    "reflect --template [topic] [--share <pool>]",
    "reflect adopt <job-id>",
    "reflect jobs",
    "reflect failure <description> [--share <pool>]",
  ],
  pool: [
    "pool create <name> [group <groupName>] | pool <name> add <text> [importance:N] | pool <name> recall|list|status|audit|ratify | pool list\n  (importance also as trailing `importance N` or `!N`; `ls` = list)",
    "pool create <name> [group <groupName>] | pool <name> add|recall|list|status|audit | pool list",
    "pool create <name> [group <groupName>]",
  ],
  guide: [
    "guide | guide <topic> | guide recall <topic> | guide list | guide audit",
    "guide recall <topic>",
  ],
  novelty: ["novelty | novelty suggest | novelty stats"],
  market: [
    "market list [open|resolved] | market search <query> | market show <id> (also view/info) | market live <venue> [duration] [limit] | market leaderboard | market score [entity] | market forecast <id>",
    "market search <query>",
    "market live <kalshi|polymarket> [duration] [limit]\nExamples:\n  market live kalshi 7d 25\n  market live polymarket 1w",
    "market show <id>   (also view/info)",
    "market forecast <id>",
  ],
  scenario: [
    "scenario extract <url> | scenario extract board <name>",
    "scenario inject <key>=<value>  (e.g. 'scenario inject fed_rate=cut')",
  ],
  position: [
    "position size <venue> <ticker> <yes|no> <our-prob 0-1> <market-price 1-99 cents>",
    "position open <venue> <ticker> <yes|no> <count> [limit-price-cents]",
    "position close <order-id> [count]",
    "position pnl [today|week|all]",
    "position confirm <proposal-id>",
    "position reject <proposal-id> [reason]",
  ],
  benchmark: [
    "benchmark sweep <name|all> [--limit N] [--seed N] [--judge M]",
    "benchmark run <name> [--limit N] [--seed N] [--model M]",
    "benchmark result <id>",
    "benchmark leaderboard <benchmark> [--limit N]",
  ],
  ask: ["ask <question>"],
  recap: ["recap <topic>  (or `recap chronicle [day|week]`)"],
  evolve: ["evolve", "evolve loop"],
  share: ["share <pool> <content>"],
  dig: ["dig <topic>"],
  skill: [
    "skill store <name> | <desc> | <actions> | skill search <query> | skill verify <id> | skill list | skill audit | skill share <id> <pool> | skill compose <id1> <id2> ... | skill import <path> (rank 3+; path under the server cwd). Example: skill store pool-recall-fanout | find a fact when one keyword misses | recall <topic> ; pool bench-facts recall <synonym> ; note the hit. See also: evolve.",
    "skill store <name> | <description> | <action_sequence>\n",
    "skill store <name> | <desc> | <actions> | skill search <query> | skill verify <id> | skill list | skill audit | skill share <id> <pool> | skill compose <id1> <id2> ... | skill import <path> (rank 3+)",
    "skill store <name> | <description> | <action_sequence>",
    "skill search <query>",
    "skill verify <id>",
    "skill share <id> <pool>",
    "skill compose <id1> <id2> [id3] ...",
    "skill import <path-to-markdown-file>",
  ],
  project: [
    "project create|list|info | project <name> orchestrate|recommend|decompose|memory|join|status|propose|tasks|budget|usage|verify|outcome",
    "project create <name> | <desc> | project <name> orchestrate|decompose|memory|join|status|propose|tasks | project list | project info <name>",
    "project create <name> | <description>",
    "project info <name>",
    "project <name> orchestrate custom <description>",
    "project <name> decompose htdag|plan-exec-verify|lazy-expansion|non-overlapping|workload-tiers|custom <desc>",
    "project <name> decompose custom <description>",
    "project <name> memory tiered|generative|graph|shared|custom <desc>",
    "project <name> memory custom <description>",
    "project <name> budget [tokens <n>] [cost <usd>] [duration <n>ms|s|m|h]",
    "project <name> usage <tokens> [cost-usd]",
    "project <name> propose <text>",
    "project <name> outcome <0..1> | <evidence-backed result and lessons>",
  ],
  experiment: [
    "experiment create <name> [arms A,B,...] [metric <name>] [goal higher|lower]",
    "experiment join <name>",
    "experiment start <name>",
    "experiment status <name>",
    "experiment results <name>",
    "experiment complete <name>",
    "experiment record <name> <arm> <metric> <value>",
    "experiment record <name> <metric> <value>",
    "experiment [list|create|join|start|status|results|complete|record]",
  ],
  observe: [
    "observe <entity> (rank 3+) | observe stats (rank 2+) | observe log <entity> (rank 7+)",
    "observe <entity> | observe stats | observe log <entity>",
    "observe log <entity>",
  ],
  trace: [
    "trace choose <models|routes|autonomous|tools> <eligible-candidate...>",
    "trace judgments <id>",
    "trace judge <id> <passed|failed|inconclusive> <criterion> | <rationale>",
  ],
  intellect: [
    "intellect create <name> | <purpose> [| contributor-ids]",
    "intellect descend <parent> <name> | <purpose>",
  ],
  journey: ["journey steer <id|latest> <context or correction>", "journey create <desire>"],
  inheritance: [
    "inheritance [list] | inheritance export <guide|tradition-pool> | inheritance import <bundle-token> (import: rank 2+; `inherit <token>` also works)",
    "inheritance [list] | inheritance export <pool> | inheritance import <bundle-token>",
    "inheritance import <bundle-token>",
  ],
  channel: [
    "channel list|listall|join|leave|send|history|create",
    "channel join <name>",
    "channel leave <name>",
    "channel send <name> <message>",
    "channel history <name> [count]",
    "channel create <name>",
    "channel list|listall|join|leave|send|history|create <name> [args]",
  ],
  crew: [
    "crew create <name> <a,b,c> [formation:<f>] [persist] -- <goal>   (also formation=<f> / --formation <f>)",
    "crew info <name>  |  crew create <name> ...",
    "crew invite <name> <agent> [role:<r>]   (also role=<r>)",
    "crew dispatch <name> <message>",
    "crew join <name>",
    "crew decline <name>",
    "crew leave <name>",
    "crew formation <name> <formation>",
    "crew persist <name>",
    "crew stage <name> <stage>",
    "crew artifact <name> <map|reduce|synthesis|draft> -- <ref>",
    "crew stall <name> <agent> [reason]",
    "crew complete <name> -- <summary>",
    "crew dissolve <name> [reason]",
  ],
  recruit: [
    "recruit match <goal> [limit=N]",
    "recruit best into <crew> for <goal> [count=N]",
    "recruit <a,b,c> into <crew> [role=<r>]",
  ],
  witness: ["witness grant <entity> <gate>"],
  conduct: [
    "conduct show <name>",
    "conduct json <name>",
    "conduct validate -- <json>",
    "conduct create <name> -- <json>",
    "conduct fork <name> <newname>",
    "conduct resolve <assignee>",
    "conduct track <name> <sampleId> predict=<0..1> [category=<c>]",
    "conduct ran <name> -- <summary>",
    "conduct outcome <name> <0..1> [category=<c>] [-- <label>]",
  ],
  board: [
    "board list|read|post|reply|search|vote|scores|pin|archive|create",
    "board read <board> [postId]",
    "board post <board> <title> | <body>",
    "board reply <postId> <body>",
    "board search <board> <query>",
    "board vote <postId> up|down [score 1-10]",
    "board scores <postId>",
    "board pin <postId>",
    "board archive <postId>",
    "board create <name>",
    "board list|read|post|reply|search|vote|scores|pin|archive|create [args]",
  ],
  group: [
    "group list|info|create|join|leave|invite|kick|promote|demote|disband",
    "group info <name>",
    "group create <id> <name>",
    "group join <name>",
    "group leave <name>",
    "group invite <entity> <group>",
    "group kick <entity> <group>",
    "group promote <entity> <group>",
    "group demote <entity> <group>",
    "group disband <name>",
    "group list|info|create|join|leave|invite|kick|promote|demote|disband [args]",
  ],
  task: [
    "task list|info|create|goal|progress|claim|heartbeat|recover|submit|approve|reject|cancel|bundle|assign|children|standing [args]",
    "task list|info|create|goal|progress|claim|heartbeat|recover|submit|approve|reject|cancel|bundle|assign|children|standing\n  task create <title> | <description> [standing:N] [bounty]   (also !N)\n  task goal <title> | <description> [priority:N]   (also !pN / --priority N)\n  task info <id>   (also show/view)",
    "task info <id>",
    "task create <title> | <description> [standing:N] [bounty]   (also !N)",
    "task goal <title> | <description> [priority:N]   (also !pN / --priority N)",
    "task progress <id> [+N | N]",
    "task claim <id>",
    "task heartbeat <id>",
    "task submit <id> <text>",
    "task approve <id> <claimant>",
    "task reject <id> <claimant>",
    "task cancel <id>",
    "task bundle <title> | <description>",
    "task assign <id> <bundle_id>",
    "task children <id>",
  ],
  macro: [
    "macro list | macro create <name> <command> | macro delete <name>",
    "macro create <name> <command>",
    "macro delete <name>",
  ],
  build: [
    "build room <id> [short description]",
    "build modify [room] <short|long|item> <value>\n  build modify short A new description\n  build modify long A longer description...\n  build modify item <key> <description>",
    "build modify item <key> <description>",
    "build link [from] <exit> <to>",
    "build unlink [from] <exit>",
    "build code <room> <typescript source>",
    "build revert <room> [version]",
    "build destroy <room>",
    "build template save <room> <name> [description]",
    "build template apply <name> <newRoomId>",
    "build template save|list|apply [args]",
    "build command create <name>",
    "build command code <name> [source]",
    "build command validate <name>",
    "build command reload <name>",
    "build command audit <name>",
    "build command destroy <name>",
    "build command create|code|validate|reload|list|audit|destroy <name>",
    "build room|modify|link|unlink|code|validate|reload|diff|audit|revert|destroy|template|command",
    "build room|modify|link|unlink|code|validate|reload|diff|audit|revert|destroy|template|command [args]",
  ],
  connect: [
    "connect add <name> <url> | connect add <name> stdio <cmd> [args] (rank 9; spawns a local process) | connect remove <name> | connect list | connect tools <name> | connect call <name> <tool> [json] | connect auth <name> bearer <token> | connect auth <name> header <key> <value>",
    "connect add|remove|list|tools|call|auth [args]",
    "connect add <name> <url> | connect add <name> stdio <command> [args]",
    "connect add <name> stdio <command> [args...]",
    "connect add <name> <url>",
    "connect remove <name>",
    "connect tools <name>",
    "connect call <server> <tool> [json-args]",
    "connect auth <name> bearer <token> | connect auth <name> header <key> <value>",
    "connect auth <name> bearer <token>",
    "connect auth <name> header <key> <value>",
  ],
  web: [
    "web search <query> | web fetch <url>",
    "web search [engines:<a,b>] [limit:N] <query>",
    "web multisearch <query1> | <query2> | <query3>",
    "web fetch <url>",
  ],
  gateway: [
    "gateway add <name> <ws-url> | gateway remove <name> | gateway list | gateway status <name> | gateway bridge <name> <channel> | gateway unbridge <name> <channel> | gateway send <name> <entity> <message>",
    "gateway add|remove|list|status|bridge|unbridge|send",
    "gateway add <name> <ws-url>",
    "gateway remove <name>",
    "gateway status <name>",
    "gateway bridge <name> <channel>",
    "gateway unbridge <name> <channel>",
    "gateway send <name> <entity> <message>",
  ],
  source: [
    "source [here|room/id] | source command <name> | source connector <name>",
    "source command <name>",
    "source connector <name>",
  ],
  batch: ["batch <commands>"],
  canvas: [
    "canvas connect <src_node_id> <tgt_node_id> <relationship>",
    "canvas disconnect <edge_id>",
    "canvas create <name> [description]",
    "canvas info <name>",
    "canvas publish <type> <asset_id> [canvas_name] [reply:<node_id>]",
    "canvas post [on:<canvas>] [reply:<node_id>] <text>",
    "canvas nodes <name>",
    "canvas delete <name>",
    "canvas edges <name>",
    "canvas intent list [canvas] | canvas intent claim <node_id> | canvas intent complete <node_id> <result>",
    "canvas intent claim <node_id>",
    "canvas intent fail <node_id> [reason]",
    "canvas intent complete <node_id> [--type <type>] <result text>",
    "canvas intent complete-rich <node_id> <a2ui_json>",
    "canvas intent list [canvas] | canvas intent claim <node_id> | ",
    "canvas layout <grid|timeline|feed> <canvas_name>",
    "canvas asset upload <url> | canvas asset list | canvas asset info <id> | canvas asset delete <id>",
    "canvas asset upload <url or file:filename>",
    "canvas asset info <id>",
    "canvas asset delete <id>",
  ],
  run: ["run quiet <binary> [args...]", "run raw <command string>"],
  shell: [
    "shell allow <binary>",
    "shell deny <binary>",
    "shell scratch cat <filename>",
    "shell scratch rm <filename>",
    "shell scratch ls | shell scratch cat <file> | shell scratch rm <file>",
    "shell save board <board_name> [title]",
    "shell save memory <key>",
    "shell save note|board|memory|canvas [args...]",
  ],
  code: [
    "code patches [pending|applied|rejected]",
    "code approval request <shell|network|secret|commit|spawn|other> <description>",
    "code approval [list|request]",
    "code skill add <name> <instructions>",
    "code skill use <name>",
    "code skill [list|add|use]",
    "code external link <acp|mcp|cursor|zed|vscode|other> <external_id>",
    "code external [show|link|unlink]",
    "code show|apply|reject <patch_id|last patch>",
    "code show <artifact_id|last|last patch|last failed>",
    "code artifacts",
    "code artifacts recent",
    "code artifacts failed",
    "code artifacts status <status>",
    "code artifacts kind <artifact_kind>",
    "code crew <goal> [with <agentA,agentB,...>]",
    "code run <typecheck|lint|test|build|dashboard:build|bun ...|git ...>",
    "code recipe save <name> <command> [then <command>...]",
    "code recipe run <name>",
    "code recipe show <name>",
    "code recipe [list|save|show|run]",
    "code exec-mode <prompt|auto|off>",
    "code exec-approve <token> [once]",
    "code exec-deny <token> [reason]",
    "code read <path>",
    "code search <query>",
    "code edit <path>[ all]\\n<<<<<<< OLD\\n{old text}\\n=======\\n{new text}\\n>>>>>>> NEW",
    "code write <path>\\n{content}",
    "code patch [title]\\n<unified diff>",
    "code profile alias <alias> <command> | code profile alias clear <alias>",
    "code profile alias clear <alias>",
    "code profile alias <alias> <command>",
    "code profile [show|list|compare|help|use|aliases]",
    "code project export [archive]",
    "code project init <name>",
    "code project clone <public-https-url> [name]",
    "code project switch <id|name>",
    "code project import <project_archive_artifact> <name>",
    "code project delete <id|name> [discard] confirm",
    "code sandbox stop [discard] confirm",
    "code sandbox ops hibernate <entity-id> confirm",
    "code sandbox ops revoke <entity-id> confirm",
    "code sandbox ops stop <entity-id> [discard] confirm",
    "code sandbox ops inventory",
    "code sandbox ops metrics",
    "code sandbox ops reconcile",
    "code sandbox ops reclaim [confirm]",
    "code service start|list|status|logs|probe|probes|screenshot|stop|restart|publish|revoke",
    "code service start <name> [--port N] -- <command> [args...]",
    "code service probes <id|name> [limit]",
    "code resume <session_id>",
    "code task <title>",
    "code model set <provider/model|agent|crew|direct>",
    "code steer <direction>",
    "code observe <what you observed>",
    "code plan|summary|handoff|decision <text>",
    "code spawn <role> <goal> | code spawn run <spawn_request>",
    "code workspace use <path>",
    "code workspace show",
    "code workspace list",
    "code workspace discover",
    "code workspace use <path>",
    "code worktree [status|on|off|merge]",
  ],
  admin: [
    "admin kick|ban|unban|bans|stats|announce|reload|export|snapshot|snapshots",
    "admin <kick|ban|unban|stats|announce|reload|export> [args]",
    "admin kick <entity>",
    "admin ban <entity> [reason]",
    "admin unban <entity>",
    "admin announce <message>",
    "admin reload <room-id>",
    "admin snapshot <name> [--force] [--compact]\n",
  ],
  agent: [
    "agent spawn <name> [model <model>] [role <role>] [key <key>] [budget <n-calls>] [thinking:off|low|medium|high] [goal <goal>]",
    "agent restart <name>",
    "agent failover <name> <provider/model>",
    "agent attention-mode <name> focused|balanced|open",
    "agent attention-feedback <name> useful|noise",
    "agent attention <name> <message>",
    "agent focus <name> <description>",
    "agent list | agent status|diagnose <name> | agent spawn|stop|restart <name> ... | agent failover <name> <provider/model> | agent attention <name> <msg> | agent attention-mode <name> focused|balanced|open | agent focus <name> <desc> | agent config <name> ...",
    "agent status <name>",
    "agent stop <name> [--keep-children]",
    "agent disable <name>",
    "agent enable <name>",
    "agent config <name> model|role|key|thinking <value>",
  ],
  productivity: [
    "productivity",
    "productivity agent <name>",
    "productivity leaderboard",
    "productivity trend",
    "productivity primitives [name]",
    "productivity prompts",
  ],
  ops: ["ops inbox", "ops ack <id>", "ops resolve <id>", "ops history", "ops recover"],
  demo: [
    "demo preflight|qualify|warm|recover|reset|status \u2014 'demo reset' needs rank 2+.",
    "demo preflight|qualify|warm|recover|reset|status",
  ],
  usecase: ["usecase info <recipe>"],
  role: [
    "role list | role view <name> [goal <text>] | role lint <name> | role diff <a> <b> | role history <name> | role create <name> [traits <t1,t2,...>] [guidelines <g1|g2|...>] [focus <f1,f2,...>] [tone <tone>] | role edit <name> ... | role reload <name> | role delete <name>",
    "role view <name>",
    "role view <name> goal <text>",
    "role history <name>",
    "role lint <name>",
    "role diff <a> <b>",
    "role reload <name>",
    "role delete <name>",
    "role list | role view <name> [goal <text>] | role lint <name> | role diff <a> <b> | role history <name> | role create <name> ... | role edit <name> ... | role reload <name> | role delete <name>",
  ],
  trait: [
    "trait list | trait view <name> | trait lint <name> | trait diff <a> <b> | trait history <name> | trait create <name> <category> <prompt> [strengths s1,s2] [preferences p1,p2] [avoids a1,a2] [domains d1,d2] [behaviors b1,b2] [antiBehaviors a1,a2] [activation a1,a2] [successSignals s1,s2] [riskSignals r1,r2] [applicableTasks t1,t2] | trait delete <name>",
    "trait view <name>",
    "trait history <name>",
    "trait lint <name>",
    "trait diff <a> <b>",
    "trait create <name> <category> <prompt text> [strengths s1,s2] [preferences p1,p2] [avoids a1,a2] [domains d1,d2] [behaviors b1,b2] [antiBehaviors a1,a2] [activation a1,a2] [successSignals s1,s2] [riskSignals r1,r2] [applicableTasks t1,t2]",
    "trait delete <name>",
  ],
  "system-prompt": ["system-prompt [role <name>] [goal <text>]"],
  key: [
    "key add <name> <provider> <value>",
    "key delete <name>",
    "key test <name>",
    "key list | key add <name> <provider> <value> | key delete <name> | key test <name>",
  ],
  adapter: [
    "adapter enable <platform> [config json]",
    "adapter disable <platform>",
    "adapter status <platform>",
    "adapter list | adapter enable <platform> | adapter disable <platform> | adapter status <platform>",
  ],
  move: ["move <direction>"],
  readiness: ["readiness", "readiness providers [name]"],
};
